/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;
import model.*;
import brain.*;
import admin.admin;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class dataLaporan extends javax.swing.JFrame {
    private TampilModel user;
    private Laporann LaporanM;
    private TampilModel[] dataLap;

    /**
     * Creates new form dataLaporan
     */
    public dataLaporan(TampilModel Akun) {
        initComponents();
        setTitle("Halaman Laporan");
        this.LaporanM = new Laporann();
        this.user = Akun;
        
        this.dataLap = this.LaporanM.laporanPetugas();
        this.showLaporann();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_batalPilih = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_beriTanggapan = new javax.swing.JButton();
        btn_verifikasiLaporan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tLaporan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DATA LAPORAN");

        btn_back.setBackground(new java.awt.Color(255, 255, 0));
        btn_back.setForeground(new java.awt.Color(0, 0, 0));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_batalPilih.setBackground(new java.awt.Color(255, 102, 102));
        btn_batalPilih.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalPilih.setText("Batal Pilih");
        btn_batalPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalPilihActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_beriTanggapan.setBackground(new java.awt.Color(102, 255, 102));
        btn_beriTanggapan.setForeground(new java.awt.Color(0, 0, 0));
        btn_beriTanggapan.setText("Beri Tanggapan");

        btn_verifikasiLaporan.setBackground(new java.awt.Color(0, 153, 0));
        btn_verifikasiLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_verifikasiLaporan.setText("Verifikasi Laporan");
        btn_verifikasiLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifikasiLaporanActionPerformed(evt);
            }
        });

        tLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Masyarakat", "Tanggal ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tLaporan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_back)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_batalPilih)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(btn_beriTanggapan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_verifikasiLaporan))
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_back))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batalPilih)
                    .addComponent(btn_verifikasiLaporan)
                    .addComponent(btn_delete)
                    .addComponent(btn_beriTanggapan))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showLaporann(){
        DefaultTableModel tabelM = (DefaultTableModel) tLaporan.getModel();
        for(int i=0; i < this.dataLap.length; i++) {
            TampilModel tampilLaporan = this.dataLap[i];
            tabelM.addRow(new String[] {
                tampilLaporan.ColumnD("id_pengaduan"),
                tampilLaporan.ColumnD("nama_masyarakat"),
                tampilLaporan.ColumnD("tgl_pengaduan"),
                tampilLaporan.ColumnD("status"),
            });
        }
    }
    
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        setVisible(false);
        new admin(this.user).setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

// Button Verifikasi
    private void btn_verifikasiLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifikasiLaporanActionPerformed
        int pilihRow = tLaporan.getSelectedRow();
        if(pilihRow>=0) {
            TampilModel pilihLaporan = this.dataLap[pilihRow];
                if(pilihLaporan.ColumnD("status").equals("0")) {
                    String id_pengaduan = this.dataLap[pilihRow].ColumnD("id_pengaduan");
                    boolean verifikasi = this.LaporanM.verification(id_pengaduan);
                        
                    if(verifikasi) {
                        stackFunction.tampilAlert(this, 1, "VERIFIED! Data Laporan terverifikasi");
                        setVisible(false);
                        new dataLaporan(this.user).setVisible(true);
                    }else{
                        stackFunction.tampilAlert(this, 0, "ERROR! Tidak Terverifkasi");
                    }
                }else{
                    stackFunction.tampilAlert(this, 0, "Already verified!");
                }
        }else{
            stackFunction.tampilAlert(this, 0, "Pilih salah satu data Laporan");
        }
    }//GEN-LAST:event_btn_verifikasiLaporanActionPerformed

    private void btn_batalPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalPilihActionPerformed
        tLaporan.clearSelection();
    }//GEN-LAST:event_btn_batalPilihActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int pilihRow = tLaporan.getSelectedRow();
        if(pilihRow >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "WARNING! Hapus data ini?");
            if(confirm == 0) {
                String id_p = this.dataLap[pilihRow].ColumnD("id_pengaduan");
                boolean hapus = this.LaporanM.delete(id_p);
                
                if(hapus) {
                    stackFunction.tampilAlert(this, 1, "SUCCESS! Data Telah dihapus");
                    stackFunction.hapusTabelRow(tLaporan, pilihRow);
                    this.dataLap = this.LaporanM.laporanPetugas();
                } else {
                    stackFunction.tampilAlert(this, 0, "UPS ERROR! Tidak dapat menghapus data");
                }
            }
            
        } else {
            stackFunction.tampilAlert(this, 0, "Pilih salah satu data jika ingin menghapus");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_batalPilih;
    private javax.swing.JButton btn_beriTanggapan;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_verifikasiLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tLaporan;
    // End of variables declaration//GEN-END:variables
}
