package admin;
import brain.*;
import model.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class dataPetugas extends javax.swing.JFrame {

    private TampilModel user;
    private Petugas PetugasM;
    private TampilModel[] dataP;
    
    public dataPetugas(TampilModel Akun) {
        setTitle("Halaman Petugas");
        initComponents();
        this.user = Akun;
        this.PetugasM = new Petugas();
        this.dataP = this.PetugasM.Petugas();
        this.tampilDataP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        btn_batalPilih = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_tambahP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPetugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_back.setBackground(new java.awt.Color(255, 255, 0));
        btn_back.setForeground(new java.awt.Color(0, 0, 0));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_batalPilih.setBackground(new java.awt.Color(255, 102, 102));
        btn_batalPilih.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalPilih.setText("Batal Pilih");
        btn_batalPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalPilihActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_tambahP.setBackground(new java.awt.Color(102, 255, 102));
        btn_tambahP.setForeground(new java.awt.Color(0, 0, 0));
        btn_tambahP.setText("Tambah Petugas");
        btn_tambahP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahPActionPerformed(evt);
            }
        });

        tPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Petugas", "Username", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tPetugas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DATA PETUGAS");

        btn_edit.setBackground(new java.awt.Color(255, 255, 102));
        btn_edit.setForeground(new java.awt.Color(0, 0, 0));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(277, 277, 277))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batalPilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambahP)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_back))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_tambahP)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_batalPilih)
                            .addComponent(btn_edit))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void tampilDataP() {
        DefaultTableModel tModel = (DefaultTableModel) tPetugas.getModel();
        for(int i=0; i < this.dataP.length; i++) {
            TampilModel cDPetugas = this.dataP[i];
            tModel.addRow(new String[] {
                cDPetugas.ColumnD("id_petugas"),
                cDPetugas.ColumnD("nama_petugas"),
                cDPetugas.ColumnD("username"),
                cDPetugas.ColumnD("level"),
            });
        }
    }
    
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
       setVisible(false);
       new admin(this.user).setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int pilihRow = tPetugas.getSelectedRow();
        if(pilihRow >= 0) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, "WARNING! Hapus data?");
            if(konfirmasi == 0) {
                String id_petugas = this.dataP[pilihRow].ColumnD("id_petugas");
                boolean hapus = this.PetugasM.delete(id_petugas);
                
                if(hapus) {
                    stackFunction.tampilAlert(this, 1, "SUCCESS! Data telah dihapus");
                    stackFunction.hapusTabelRow(tPetugas, pilihRow);
                    this.dataP = this.PetugasM.Petugas();
                } else {
                    stackFunction.tampilAlert(this, 0, "ERROR! Data tidak dapat dihapus");
                }
            }
            
        } else {
            stackFunction.tampilAlert(this, 0, "Harap pilih data petugas terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int pilihRow = tPetugas.getSelectedRow();
        if(pilihRow>=0) {
            TampilModel pilihPetugas = this.dataP[pilihRow];
            setVisible(false);
            new editPetugas(this.user, pilihPetugas).setVisible(true);
            
        } else {
            stackFunction.tampilAlert(this, 0, "Pilih salah satu data yang ingin diedit");
        }
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_tambahPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahPActionPerformed
        setVisible(false);
        new tambahPetugas(this.user).setVisible(true);
    }//GEN-LAST:event_btn_tambahPActionPerformed

    private void btn_batalPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalPilihActionPerformed
       tPetugas.clearSelection();
    }//GEN-LAST:event_btn_batalPilihActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_batalPilih;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_tambahP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPetugas;
    // End of variables declaration//GEN-END:variables
}
