package masyarakat;
import model.*;
import brain.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ILHAM
 */
public class Home extends javax.swing.JFrame {
    private TampilModel user;
    private Laporann LaporanM;
    private TampilModel[] dataLap;
    
    /**
     * Creates new form Home
     */
    public Home(TampilModel Akun) {
        setTitle("Halaman Masyarakat");
        this.LaporanM = new Laporann();
        initComponents();
        
        this.user = Akun;
        kNik.setText(this.user.ColumnD("nik"));
        kNama.setText(this.user.ColumnD("nama"));
        kTelepon.setText(this.user.ColumnD("telp"));
        
        this.dataLap = this.LaporanM.semuaLaporan();
        this.showLaporan();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kNik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kTelepon = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kSubjek = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporan = new javax.swing.JTable();
        btn_Detail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kisiLap = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Profile");

        jLabel2.setText("NIK");

        kNik.setEditable(false);
        kNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kNikActionPerformed(evt);
            }
        });

        jLabel3.setText("NAMA");

        kNama.setEditable(false);
        kNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kNamaActionPerformed(evt);
            }
        });

        jLabel4.setText("NO TELEPON");

        kTelepon.setEditable(false);
        kTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTeleponActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("BUAT LAPORAN BARU");

        jLabel6.setText("SUBJEK");

        kSubjek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kSubjekActionPerformed(evt);
            }
        });

        jLabel7.setText("ISI LAPORAN");

        btnReset.setBackground(new java.awt.Color(255, 51, 51));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(0, 204, 0));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("RIWAYAT LAPORAN");

        tableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "TANGGAL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLaporan.setEnabled(false);
        jScrollPane1.setViewportView(tableLaporan);

        btn_Detail.setBackground(new java.awt.Color(0, 102, 0));
        btn_Detail.setText("DETAIL");
        btn_Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DetailActionPerformed(evt);
            }
        });

        kisiLap.setColumns(20);
        kisiLap.setRows(5);
        jScrollPane2.setViewportView(kisiLap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(kSubjek)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_submit))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(37, 37, 37)
                        .addComponent(btn_Detail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kNik, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kNama, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logout)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kNik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kSubjek, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Detail)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btnReset))
                .addGap(784, 784, 784))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showLaporan() {
        DefaultTableModel ModelTabel = (DefaultTableModel) tableLaporan.getModel();
        for(int i=0; i<this.dataLap.length; i++){
        TampilModel sLaporan = this.dataLap[i];
            ModelTabel.addRow(new String[]{
                sLaporan.ColumnD("id_pengaduan"),
                sLaporan.ColumnD("tgl_pengaduan"),
                sLaporan.ColumnD("status"),
            });
        }
    }
    
    private void kNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kNikActionPerformed

    private void kNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kNamaActionPerformed

    private void kTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kTeleponActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        stackFunction.logout(this);
    }//GEN-LAST:event_logoutActionPerformed

    private void kSubjekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kSubjekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kSubjekActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kSubjek.setText("");
        kisiLap.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String sub = kSubjek.getText();
        String isiLap = kisiLap.getText();
        
        boolean kirim = this.LaporanM.tambahLap(new String[]{
            this.user.ColumnD("nik"),
            stackFunction.tanggal(),
            sub,
            isiLap,
            "0",    
        });
        if(kirim) {
            stackFunction.tampilAlert(this, 1, "Laporan Success Terkirim!");
            this.btnResetActionPerformed(evt);
            this.dataLap = this.LaporanM.semuaLaporan();
            
            TampilModel LaporanNew = this.dataLap[this.dataLap.length - 1];
            DefaultTableModel tableModel = (DefaultTableModel) btn_submit.getModel();
            tableModel.addRow(new String[] {
                LaporanNew.ColumnD("id_pengaduan"),
                LaporanNew.ColumnD("tgl_pengaduan"),
                LaporanNew.ColumnD("status"),
            });
        }
        else{
            stackFunction.tampilAlert(this, 0, "ERROR! Laporan tidak dapat terkirim");
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DetailActionPerformed
        int pilihRow = tableLaporan.getSelectedRow();
        if(pilihRow >=0) {
            TampilModel pilihLaporan = this.dataLap[pilihRow];
            setVisible(false);
            new detailLaporan(this.user, pilihLaporan).setVisible(true);
        }else{
            stackFunction.tampilAlert(this, 0, "Tidak ada data yang dipilih");
        }
    }//GEN-LAST:event_btn_DetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btn_Detail;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kNama;
    private javax.swing.JTextField kNik;
    private javax.swing.JTextField kSubjek;
    private javax.swing.JTextField kTelepon;
    private javax.swing.JTextArea kisiLap;
    private javax.swing.JButton logout;
    private javax.swing.JTable tableLaporan;
    // End of variables declaration//GEN-END:variables
}
